Repository cilium/cilium-cli, pull requests merged in 2021-08, with the labels that each got.

#471 workflows: display logs in job execution step
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge, area/CI

#474 workflows: fix logs not being displayed on failure
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI

#444 test: Add error detail to ipcache check failures
  connectivity/check/deployment.go
Labels: area/CI

#443 k8s: Use TTY to cancel execution
  connectivity/check/action.go
  connectivity/check/deployment.go
  connectivity/check/policy.go
  internal/k8s/client.go
  internal/k8s/exec.go
  internal/utils/ctrlcreader.go
Labels: ready-to-merge

#478 add hubble-ui status
  status/k8s.go
Labels: ready-to-merge

#422 test: Validate Service IP
  connectivity/check/deployment.go
Labels: area/CI

#325 main: Add gops agent
  cmd/cilium/main.go
  go.mod
  go.sum
  vendor/github.com/google/gops/LICENSE
  vendor/github.com/google/gops/agent/agent.go
  vendor/github.com/google/gops/agent/sockopt_unix.go
  vendor/github.com/google/gops/agent/sockopt_unsupported.go
  vendor/github.com/google/gops/internal/internal.go
  vendor/github.com/google/gops/internal/internal_go1_13.go
  vendor/github.com/google/gops/internal/internal_lt_go1_13.go
  vendor/github.com/google/gops/signal/signal.go
  vendor/github.com/shirou/gopsutil/v3/internal/common/common.go
  vendor/github.com/shirou/gopsutil/v3/mem/mem_openbsd_arm64.go
  vendor/github.com/xlab/treeprint/README.md
  vendor/github.com/xlab/treeprint/go.mod
  vendor/github.com/xlab/treeprint/go.sum
  vendor/github.com/xlab/treeprint/treeprint.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/modules.txt
Labels: enhancement
