Repository cilium/cilium-cli, pull requests merged in 2021-05, with the labels that each got.

#242 make: use local golangci-lint binary to run static checks when available
  Makefile
Labels: enhancement

#249 github: Remove `kubectl wait` commands from Kind workflow
  .github/workflows/kind.yaml
Labels: bug

#244 .github: Stop running tests for every push to master
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#210 release: pin skx/github-action-publish-binaries to a specific sha
  .github/workflows/release.yaml
Labels: ready-to-merge

#246 .github: Speed up cluster cleanups
  .github/workflows/aks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#254 install: fix rollback for operator deployment
  install/certs.go
  install/encryption.go
  install/install.go
Labels: bug, ready-to-merge

#235 feat: print out user datapath model
  install/autodetect.go
Labels: ready-to-merge

#258 CODEOWNERS: Assign `connectivity/` to cilium/policy
  CODEOWNERS
Labels: ready-to-merge

#252 azure: refactor subscription handling + small improvements
  install/azure.go
  install/install.go
  internal/cli/cmd/install.go
Labels: enhancement, ready-to-merge
