Repository cilium/cilium-cli, pull requests merged in 2021-09, with the labels that each got.

#485 Fix flow validation breakage
  connectivity/check/action.go
Labels: bug, ready-to-merge

#318 test: validate exit code and add HTTP drop testing
  connectivity/check/action.go
  connectivity/check/peer.go
  connectivity/check/policy.go
  connectivity/filters/filters.go
  connectivity/suite.go
  connectivity/tests/common.go
  connectivity/tests/service.go
  connectivity/tests/world.go
Labels: enhancement

#511 Switch pod to world testing from `cilium.io` to `one.one.one.one`
  connectivity/manifests/client-egress-l7-http.yaml
  connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
  connectivity/suite.go
  connectivity/tests/world.go
Labels: area/CI

#526 go.mod, vendor: update hubble to v0.8.1
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/modules.txt
Labels: ready-to-merge

#532 test: Always deploy `client2` on same node as `client`
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#546 connectivity/check: use correct ServicePort name
  connectivity/check/deployment.go
Labels: ready-to-merge

#555 .github/workflows: install Go for `go run` in multicluster job
  .github/workflows/multicluster.yaml
Labels: area/CI

#553 .github: let dependabot ignore k8s deps
  .github/dependabot.yml
Labels: area/CI

#560 Disable cfssl log messages
  README.md
  cmd/cilium/main.go
  internal/logging/logging.go
Labels: ready-to-merge
