Repository cilium/cilium-cli, pull requests merged in 2021-04, with the labels that each got.

#178 clustermesh: Fix clustermesh status when clusters are not connected
  clustermesh/clustermesh.go
Labels: bug

#170 relay: add constants for the service port
  defaults/defaults.go
  hubble/relay.go
Labels: enhancement

#184 test: Change `--test` args to regexp matches
  connectivity/check/check.go
  internal/cli/cmd/connectivity.go
Labels: enhancement

#183 check: Skip SYN-ACK validation when flow aggregation is on (again)
  connectivity/check/check.go
Labels: bug, enhancement
