Repository cilium/cilium-cli, pull requests merged in 2021-07, with the labels that each got.

#385 clustermesh: only wait for apiserver deployment if `--wait` is specified
  clustermesh/clustermesh.go
Labels: bug, ready-to-merge

#386 workflows: do not wait when installing on Kind
  .github/workflows/kind.yaml
Labels: bug, enhancement

#336 misc: use hubble command rather than port-forwards
  .github/workflows/kind.yaml
  README.md
  connectivity/check/context.go
Labels: area/CI, ready-to-merge

#324 k8s: Use TTY to cancel execution
  connectivity/check/action.go
  connectivity/check/deployment.go
  connectivity/check/policy.go
  internal/k8s/exec.go
  internal/utils/ctrlcreader.go
Labels: enhancement

#393 vendor: remove direct dependency on github.com/golang/protobuf
  connectivity/check/action.go
  go.mod
  go.sum
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/modules.txt
Labels: enhancement

#396 ci/multicluster: Run sysdump in both clusters
  .github/workflows/multicluster.yaml
Labels: area/CI

#391 workflows: enhance `aws-node` DaemonSet testing
  .github/in-cluster-test-scripts/eks-uninstall.sh
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
Labels: area/CI

#411 clustermesh: Support --config option
  clustermesh/clustermesh.go
  internal/cli/cmd/clustermesh.go
Labels: ready-to-merge

#121 version: report the cilium images version
  internal/cli/cmd/version.go
Labels: enhancement

#420 .github/workflows: use latest eksctl version
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
Labels: ready-to-merge

#415 connectivity/check: support running on Cilium 1.8
  connectivity/check/deployment.go
Labels: ready-to-merge

#423 workflows: use latest stable CLI in post-test information gathering
  .github/in-cluster-test-scripts/eks-tunnel.sh
  .github/in-cluster-test-scripts/eks.sh
  .github/in-cluster-test-scripts/external-workloads.sh
  .github/in-cluster-test-scripts/gke.sh
  .github/in-cluster-test-scripts/multicluster.sh
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI

#429 sysdump: report errors per task
  go.mod
  go.sum
  sysdump/sysdump.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: ready-to-merge

#400 .github: create clusters with taints
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
  defaults/defaults.go
Labels: ready-to-merge

#390 workflows: check status of Relay port-forward
  .github/in-cluster-test-scripts/eks-tunnel.sh
  .github/in-cluster-test-scripts/eks.sh
  .github/in-cluster-test-scripts/gke.sh
  .github/in-cluster-test-scripts/multicluster.sh
  .github/workflows/aks.yaml
  .github/workflows/kind.yaml
Labels: area/CI, ready-to-merge

#442 workflows: refactor EKS workflows
  .github/in-cluster-test-scripts/eks-install.sh
  .github/in-cluster-test-scripts/eks-tunnel-install.sh
  .github/in-cluster-test-scripts/eks-tunnel.sh
  .github/in-cluster-test-scripts/eks-uninstall.sh
  .github/in-cluster-test-scripts/eks.sh
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
Labels: area/CI

#441 workflows: add warning/explanation for testing workflow changes
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI, ready-to-merge

#438 .github/workflows: verify checksum when installing latest stable CLI
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#450 workflows: add test exceptions to EKS tunnel workflow
  .github/in-cluster-test-scripts/eks-tunnel.sh
Labels: area/CI

#451 workflows: fix in-cluster job kubectl wait
  .github/workflows/aks.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI, ready-to-merge

#452 workflows: fix test exceptions to EKS tunnel workflow
  .github/in-cluster-test-scripts/eks-tunnel.sh
Labels: area/CI, ready-to-merge

#454 workflows: fix external workloads GCP VM image
  .github/workflows/externalworkloads.yaml
Labels: area/CI, ready-to-merge
