Repository cilium/cilium-cli, pull requests merged in 2021-06, with the labels that each got.

#264 install: gofmt
  install/azure.go
  install/install.go
Labels: ready-to-merge

#266 CODEOWNERS: Update for cilium/ci-structure
  CODEOWNERS
Labels: ready-to-merge

#280 github: Add --timestamps to cilium vm logs
  .github/workflows/externalworkloads.yaml
Labels: enhancement, ready-to-merge

#283 CODEOWNERS: Give maintainer's code to github-sec team
  CODEOWNERS
Labels: ready-to-merge

#279 test: Add progress indicator when buffering logs
  connectivity/check/action.go
  connectivity/check/logging.go
Labels: enhancement, ready-to-merge

#306 getFlows: support deadline flow returns
  connectivity/check/action.go
Labels: ready-to-merge

#322 CODEOWNERS: Assign /connectivity to @cilium/cli
  CODEOWNERS
Labels: ready-to-merge

#323 azure: fix Service Principal creation
  install/azure.go
Labels: bug, ready-to-merge

#309 Prepare for v0.8 release
  VERSION
Labels: ready-to-merge

#337 install: fix minikube exec command
  install/minikube.go
Labels: bug, ready-to-merge

#332 hubble: fix opening Hubble UI URL on platforms other than macOS
  go.mod
  go.sum
  hubble/ui.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_freebsd.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/github.com/pkg/browser/go.mod
  vendor/github.com/pkg/browser/zbrowser_windows.go
  vendor/modules.txt
Labels: ready-to-merge

#346 check: Wait for nodeports
  connectivity/check/deployment.go
Labels: ready-to-merge

#317 test: Treat hubble errors as warnings rather than failures
  connectivity/check/action.go
Labels: enhancement, ready-to-merge

#297 test: Retry harder if hubble returns no flows
  connectivity/check/action.go
Labels: enhancement, ready-to-merge

#343 Release v0.8.1
  VERSION
Labels: ready-to-merge

#345 install: wait until Cilium DS is up and running before restarting pods
  install/install.go
  internal/cli/cmd/install.go
Labels: ready-to-merge

#356 Partially Revert #277
  connectivity/check/deployment.go
Labels: ready-to-merge

#350 ci: fix the go vendoring check
  .github/workflows/go.yml
Labels: area/CI

#360 install/aks: set 'enable-ipv4-masquerade' as false
  install/install.go
Labels: bug

#208 install: don't delete the 'aws-node' DaemonSet
  .github/workflows/eks.yaml
  install/aws.go
  install/install.go
  install/uninstall.go
Labels: ready-to-merge

#366 workflows: Add `--timestamps` to `kubectl logs`
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#341 workflows: refactor firewall rule name in multicluster test
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#339 workflows: remove test exception from EKS
  .github/in-cluster-test-scripts/eks.sh
Labels: ready-to-merge

#380 Set the default code owner to @cilium/cli
  CODEOWNERS
Labels: ready-to-merge

#236 sysdump: support collecting eks-specific data
  internal/k8s/client.go
  sysdump/client.go
  sysdump/constants.go
  sysdump/sysdump.go
Labels: enhancement

#338 workflows: invert external workloads setup
  .github/workflows/externalworkloads.yaml
Labels: area/CI, bug

#387 Update kind and helm/kind-action
  .github/workflows/kind.yaml
Labels: ready-to-merge
