Repository cilium/cilium-cli, pull requests merged in 2022-02, with the labels that each got.

#718 azure: add Contributor privileges to new Service Principals
  .github/workflows/aks.yaml
  install/azure.go
Labels: area/CI

#720 Use specific policy depending on Cilium version
  connectivity/check/context.go
  connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
  connectivity/suite.go
Labels: release-blocker/v0.10.4

#728 sysdump: include own log messages in sysdump
  internal/cli/cmd/sysdump.go
  sysdump/defaults.go
  sysdump/sysdump.go
  sysdump/sysdump_test.go
Labels: ready-to-merge
