Repository cilium/cilium-cli, pull requests merged in 2022-11, with the labels that each got.

#1191 defaults: Update cilium/json-mock to v1.3.3
  defaults/defaults.go
Labels: kind/bug, area/CI

#1203 test/connectivity: Add a bit more logging around Hubble connections
  connectivity/check/action.go
Labels: ready-to-merge

#1212 Update stable release to v0.12.6
  stable.txt
Labels: ready-to-merge

#1215 Get rid of kube-proxy-replacement=probe
  .github/workflows/kind.yaml
  internal/cli/cmd/install.go
Labels: kind/enhancement

#1216 clustermesh: Rename host-reachable-svc opt
  clustermesh/clustermesh.go
Labels: kind/enhancement

#1219 connectivity: Send request to 1.1.1.1 over TCP/443 instead of TCP/80
  connectivity/tests/cidr.go
Labels: ready-to-merge

#1218 install: allow for multiple roles and rolebindings per file
  install/install.go
  install/rbac.go
  internal/utils/yaml.go
Labels: ready-to-merge

#1233 connectivity: collect sysdump also on test setup failure
  connectivity/check/action.go
  connectivity/check/context.go
  connectivity/check/test.go
Labels: area/CI, ci/hyperjump

#1238 clustermesh: Fix --bpf-lb-sock on < 1.12
  clustermesh/clustermesh.go
Labels: ready-to-merge
