Repository cilium/cilium-cli, pull requests merged in 2022-12, with the labels that each got.

#1251 workflows: add wait for no operation for cleaning up GKE
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#1252 Prepare for v0.12.11 release
  README.md
Labels: ready-to-merge

#1261 connectivity: Reorder L7 ingress connectivity tests
  connectivity/suite.go
Labels: kind/bug

#1262 workflows: Bump timeout for EKS workflow
  .github/workflows/eks.yaml
Labels: area/CI

#1263 workflows: Collect sysdump immediately after test failures
  .github/in-cluster-test-scripts/aks.sh
  .github/in-cluster-test-scripts/eks-tunnel.sh
  .github/in-cluster-test-scripts/eks.sh
  .github/in-cluster-test-scripts/external-workloads.sh
  .github/in-cluster-test-scripts/gke.sh
  .github/in-cluster-test-scripts/multicluster.sh
  .github/workflows/kind.yaml
Labels: area/CI

#1268 workflows: Bump timeout for External Workload workflow
  .github/workflows/externalworkloads.yaml
Labels: area/CI

#1264 Update stable release to v0.12.11
  stable.txt
Labels: ready-to-merge

#1281 workflows: Test with Cilium v1.12.4
  .github/workflows/aks-azure-ipam.yaml
  .github/workflows/aks-byocni.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI

#1291 sysdump: Fix empty namespace error
  sysdump/sysdump.go
  sysdump/sysdump_test.go
Labels: kind/bug, area/sysdump

#1295 connectivity: Fix tunnel feature detection
  connectivity/check/features.go
Labels: kind/bug

#1299 k8s: Bring back TTY to Exec
  connectivity/tests/encryption.go
  internal/utils/ctrlcreader.go
  k8s/client.go
  k8s/copy.go
  k8s/exec.go
Labels: area/CI

#1304 connectivity: Fix iface derivation in encrypt tests
  connectivity/tests/encryption.go
Labels: kind/bug, ready-to-merge, area/CI
