Repository cilium/cilium-cli, pull requests merged in 2022-04, with the labels that each got.

#785 hubble: fix deployment of hubble with unreleased Cilium versions
  hubble/hubble.go
  hubble/relay.go
Labels: release-blocker/v0.11.0

#788 vendor: Update github.com/cilium/charts
  go.mod
  go.sum
  vendor/github.com/cilium/charts/README.md
  vendor/github.com/cilium/charts/cilium-1.12.0-rc1.tgz
  vendor/github.com/cilium/charts/index.yaml
  vendor/modules.txt
Labels: release-blocker/v0.11.0

#789 hubble: fix installation of 1.10 versions
  hubble/relay.go
  hubble/ui.go
Labels: release-blocker/v0.11.0

#784 hubble: redact cilium-ca certificate key when printing to terminal
  hubble/hubble.go
  install/uninstall.go
  internal/certs/certs.go
  internal/cli/cmd/hubble.go
  internal/cli/cmd/install.go
Labels: ready-to-merge, release-blocker/v0.11.0

#793 helm: fix helm template output for extraConfig options
  internal/helm/helm.go
Labels: kind/bug

#792 Transform flags context and namespace to be global for cilium-cli
  internal/cli/cmd/clustermesh.go
  internal/cli/cmd/cmd.go
  internal/cli/cmd/config.go
  internal/cli/cmd/connectivity.go
  internal/cli/cmd/context.go
  internal/cli/cmd/hubble.go
  internal/cli/cmd/install.go
  internal/cli/cmd/status.go
  internal/cli/cmd/sysdump.go
  internal/cli/cmd/version.go
Labels: ready-to-merge

#807 install: add support for AWS with CNI chaining
  install/install.go
Labels: ready-to-merge

#818 install: add encryption.enabled when encryption wireguard is used
  install/helm.go
Labels: kind/bug, ready-to-merge

#823 Extract all deamonsets of Cilium
  sysdump/sysdump.go
Labels: ready-to-merge

#820 install: Wait for test pods to be cleaned up
  install/uninstall.go
Labels: ready-to-merge, area/CI
