Repository cilium/cilium-cli, pull requests merged in 2022-08, with the labels that each got.

#999 Update Go to 1.18.5
  .github/workflows/go.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
  .github/workflows/release.yaml
  Makefile
Labels: ready-to-merge

#1002 internal: add missing types when generating helm template command
  internal/helm/helm.go
Labels: kind/bug

#981 connectivity: Add -t to prefix log msg with timestamp
  connectivity/check/check.go
  connectivity/check/context.go
  connectivity/check/logging.go
  internal/cli/cmd/connectivity.go
Labels: kind/enhancement

#1000 v0.10: Update Go to 1.18.5
  .github/workflows/go.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
  .github/workflows/release.yaml
  Makefile
Labels: backport/0.10

#1011 .github: update dependabot open PR limit for GH actions
  .github/dependabot.yml
Labels: ready-to-merge

#1003 ci: fix AKS testing on `v0.10`
  .github/workflows/aks.yaml
Labels: area/CI, backport/0.10

#1022 connectivity: Use agent-runtime-config.json for feature detection
  connectivity/check/features.go
Labels: ready-to-merge

#1033 Update stable release to v0.12.1
  stable.txt
Labels: ready-to-merge

#1056 Clustermesh secrets helm inconsistency fix
  clustermesh/clustermesh.go
  defaults/defaults.go
Labels: kind/bug
