Repository cilium/cilium-cli, pull requests merged in 2022-06, with the labels that each got.

#888 install: Add --list-versions flag
  go.mod
  install/install.go
  internal/cli/cmd/install.go
  internal/helm/helm.go
Labels: needs-rebase

#896 ci: create a new subnetwork for each new GKE cluster
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: area/CI

#897 Update Go to 1.18.3, golangci-lint to 1.46.2
  .github/workflows/go.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
  .github/workflows/release.yaml
  Makefile
Labels: ready-to-merge

#911 vendor: update yaml.v3 to v3.0.1
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: kind/bug, ready-to-merge

#923 v0.10: ci: create a new subnetwork for each new GKE cluster
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: backport/0.10

#926 Use OCI container reference parser to extract Cilium's version
  go.mod
  go.sum
  k8s/client.go
  k8s/client_test.go
  vendor/github.com/distribution/distribution/LICENSE
  vendor/github.com/distribution/distribution/reference/helpers.go
  vendor/github.com/distribution/distribution/reference/normalize.go
  vendor/github.com/distribution/distribution/reference/reference.go
  vendor/github.com/distribution/distribution/reference/regexp.go
  vendor/modules.txt
Labels: ready-to-merge
