Repository cilium/cilium-cli, pull requests merged in 2022-07, with the labels that each got.

#953 azure: fix BYOCNI install with Cilium >= 1.12
  install/install.go
Labels: ready-to-merge

#960 connectivity: Update coredns image for arm64
  connectivity/check/deployment.go
Labels: ready-to-merge

#968 ci: switch to OIDC authentication for az CLI
  .github/workflows/aks-azure-ipam.yaml
  .github/workflows/aks-byocni.yaml
Labels: ready-to-merge, area/CI

#973 [connectivity tests] Support private CoreDNS image location
  connectivity/check/check.go
  connectivity/check/deployment.go
  defaults/defaults.go
  internal/cli/cmd/connectivity.go
Labels: needs-rebase

#986 ci: explicitly wait for cilium status after enabling Hubble relay on GKE
  .github/in-cluster-test-scripts/external-workloads-install.sh
  .github/in-cluster-test-scripts/gke.sh
  .github/in-cluster-test-scripts/multicluster.sh
Labels: ready-to-merge

#992 RELEASE.md: bump version in stable.txt after release
  RELEASE.md
Labels: ready-to-merge

#995 connectivity: Add node-local-dns match labels
  connectivity/manifests/client-egress-only-dns.yaml
  connectivity/manifests/client-egress-to-echo.yaml
  connectivity/manifests/client-egress-to-entities-world.yaml
  connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
Labels: ready-to-merge
