Repository cilium/cilium-cli, pull requests merged in 2022-05, with the labels that each got.

#826 install: don't repeat log message when waiting for test namespace to be deleted
  install/uninstall.go
Labels: ready-to-merge

#837 clustermesh: Run `cilium` with sudo in VM install script
  clustermesh/clustermesh.go
Labels: kind/bug, area/clustermesh

#878 ingress: Create ingress class if required.
  install/install.go
Labels: ready-to-merge

#883 install: Wait for test pods to be cleaned up
  install/uninstall.go
Labels: backport/0.10
