Repository cilium/cilium-cli, pull requests merged in 2023-09, with the labels that each got.

#1948 Explicitly configure ClusterID/Name in external workloads script
  clustermesh/clustermesh.go
Labels: ready-to-merge

#1952 connectivity: Delete test-conn-disrupt pods after running tests
  connectivity/check/context.go
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#1955 connectivity: Decrease test-conn-disrupt-client interval to 10ms
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#1959 connectivity: Expose test-conn-disrupt dispatch period
  connectivity/check/check.go
  connectivity/check/deployment.go
  internal/cli/cmd/connectivity.go
Labels: area/CI

#1965 connectivity: convert conn-disrupt-dispatch-interval to duration
  connectivity/check/check.go
  connectivity/check/deployment.go
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge

#1967 Prepare for v0.15.8 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#1938 clustermesh: Add support for kubernetes service annotations
  clustermesh/clustermesh.go
  internal/cli/cmd/clustermesh.go
Labels: ready-to-merge

#1972 make: use short golangci-lint version format when comparing versions
  Makefile
Labels: ready-to-merge

#1978 check: export label prefixes constants
  connectivity/check/test.go
Labels: ready-to-merge

#1990 Clean up the node feature detection logic
  connectivity/check/context.go
  connectivity/check/deployment.go
  connectivity/check/features.go
Labels: ready-to-merge

#1986 utils: export WaitObserver methods into wait package
  clustermesh/clustermesh.go
  connectivity/tests/egressgateway.go
  internal/utils/utils.go
  utils/wait/wait.go
Labels: ready-to-merge

#1991 Refactor extractFeaturesFromConfigMap
  connectivity/check/features.go
  connectivity/check/features_test.go
Labels: ready-to-merge

#1992 sysdump: Cache Cilium pods and cilium-config ConfigMap
  sysdump/sysdump.go
  sysdump/sysdump_test.go
Labels: ready-to-merge
