Repository cilium/cilium-cli, pull requests merged in 2023-10, with the labels that each got.

#1993 install: Avoid using deprecated "tunnel" flag
  clustermesh/clustermesh.go
  install/helm.go
  install/install.go
Labels: ready-to-merge

#2002 clustermesh: Adapt clustermesh script to install cilium-dbg
  clustermesh/clustermesh.go
Labels: ready-to-merge

#2007 connectivity test: Fix detectFeatures() logic
  connectivity/check/features.go
Labels: ready-to-merge

#2004 sysdump: Detect features from cilium-config ConfigMap
  sysdump/sysdump.go
Labels: ready-to-merge

#1845 Pick up SPIRE status messages from cilium-agent
  status/status.go
Labels: ready-to-merge

#2024 Update stable release to v0.15.10
  stable.txt
Labels: ready-to-merge

#2025 sysdump: Detect if Gateway API support is enabled
  sysdump/sysdump.go
  utils/features/features.go
Labels: ready-to-merge

#2032 sysdump feature detection: Don't depend on Cilium version
  connectivity/check/features.go
  sysdump/sysdump.go
  utils/features/features.go
  utils/features/features_test.go
Labels: ready-to-merge

#2046 Update stable release to v0.15.11
  stable.txt
Labels: ready-to-merge

#2047 echo-external-node: Check if NodeWithoutCilium is enabled
  connectivity/check/deployment.go
Labels: ready-to-merge

#2049 action: Do not install released vsn if CI vsn is specified
  action.yaml
Labels: area/CI

#2045 gha: cleanup stale AWS-CNI iptables rules in EKS tunnel workflow
  .github/in-cluster-test-scripts/eks-tunnel.sh
Labels: ready-to-merge

#2054 sysdump: Check if enable-envoy-config is set
  sysdump/sysdump.go
  utils/features/features.go
Labels: ready-to-merge

#2058 action: Allow users to skip building CLI
  action.yaml
Labels: ready-to-merge, area/CI
