Repository cilium/cilium-cli, pull requests merged in 2023-02, with the labels that each got.

#1353 Check if context is cancelled before next iteration
  connectivity/tests/health.go
Labels: ready-to-merge

#1362 clustermesh: Add missing brackets of etcd option
  clustermesh/clustermesh.go
Labels: kind/bug, ready-to-merge, area/clustermesh

#1359 clustermesh: adapt global service annotations
  connectivity/check/deployment.go
Labels: area/clustermesh

#1364 connectivity: drop pre-1.11 allow-except-world test
  connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
  connectivity/suite.go
Labels: ready-to-merge

#1367 go.mod, vendor: update github.com/cilium/hubble to v0.11.1
  go.mod
  go.sum
  vendor/github.com/cilium/hubble/pkg/printer/color.go
  vendor/github.com/cilium/hubble/pkg/printer/formatter.go
  vendor/github.com/cilium/hubble/pkg/printer/options.go
  vendor/github.com/cilium/hubble/pkg/printer/printer.go
  vendor/modules.txt
Labels: ready-to-merge

#958 Add JSON status (fix #956)
  clustermesh/clustermesh.go
  internal/cli/cmd/clustermesh.go
  internal/cli/cmd/status.go
  status/k8s.go
  status/status.go
Labels: priority/release-blocker

#1401 connectivity: skip nodeport tests with clustermesh if KPR is disabled
  connectivity/suite.go
Labels: area/clustermesh

#1404 ingress: Create Ingress Service if required
  install/install.go
Labels: kind/bug

#1392 Wait for deletion of agent DaemonSet before deleting other resources.
  install/uninstall.go
Labels: ready-to-merge

#1399 defaults: Lower connectivity timeouts
  defaults/defaults.go
Labels: ready-to-merge, area/CI

#1384 test: Wait for policy change if any policy changed
  connectivity/check/policy.go
Labels: kind/bug

#1383 status: detect when DaemonSets and Deployments are rolling out
  status/k8s.go
  status/k8s_test.go
Labels: ready-to-merge
