Repository cilium/cilium-cli, pull requests merged in 2023-12, with the labels that each got.

#2143 install action: Ignore .git and vendor directories
  action.yaml
Labels: ready-to-merge

#2146 connectivity test: check for deleted cilium agent pod in health probe
  connectivity/tests/health.go
Labels: ready-to-merge

#2145 connectivity test: introduce connectivity test suite timeout flag
  connectivity/check/check.go
  defaults/defaults.go
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge

#2150 Prepare for v0.15.17 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#2153 Update stable release to v0.15.17
  stable.txt
Labels: ready-to-merge

#2156 connectivity: Set test-conn-disrupt dispatch interval to 0ms
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge, area/CI

#2158 Remove Cilium v1.11 from the version list
  README.md
Labels: ready-to-merge

#2176 kind: Set conn-disrupt-test-setup
  .github/workflows/kind.yaml
Labels: ready-to-merge, area/CI

#2165 connectivity: Bump test-connection-disruption img to v0.0.13
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#2179 Update stable release to v0.15.18
  stable.txt
Labels: ready-to-merge

#2168 Move perf test command to separate subcommand
  .github/in-cluster-test-scripts/aks.sh
  .github/in-cluster-test-scripts/eks-tunnel.sh
  .github/in-cluster-test-scripts/eks.sh
  .github/in-cluster-test-scripts/external-workloads.sh
  .github/in-cluster-test-scripts/gke.sh
  README.md
  connectivity/check/action.go
  connectivity/check/check.go
  connectivity/check/context.go
  connectivity/check/deployment.go
  connectivity/perf/benchmarks/netperf/perfpod.go
  connectivity/perf/common/metrics.go
  connectivity/suite.go
  connectivity/tests/perfpod.go
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge, kind/enhancement
