Repository cilium/cilium-cli, pull requests merged in 2023-05, with the labels that each got.

#1563 Add GHA to install Cilium CLI executable
  action.yaml
Labels: area/CI

#1560 helm mode: Make Helm chart repository configurable
  defaults/defaults.go
  install/install.go
  internal/cli/cmd/install.go
  internal/helm/helm.go
  internal/helm/helm_test.go
Labels: ready-to-merge

#1547 connectivity: test accessing NodePort from outside with L7 policy
  connectivity/manifests/echo-ingress-l7-http-from-anywhere.yaml
  connectivity/suite.go
Labels: ready-to-merge, area/CI

#1540 connectivity: add retry to external targets
  connectivity/check/check.go
  connectivity/suite.go
  connectivity/tests/common.go
  connectivity/tests/to-cidr.go
  connectivity/tests/world.go
  defaults/defaults.go
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge

#1570 connectivity: report peer name in "no flows recorded" log message
  connectivity/check/action.go
Labels: ready-to-merge

#1587 connectivity: Fix IPv6 skipping when EP routes are on
  connectivity/check/test.go
Labels: ready-to-merge, area/CI

#1551 helm mode: add additional deprecated secret logic, and fix `clustermesh connect` for helm mode
  clustermesh/certs.go
  clustermesh/clustermesh.go
  defaults/defaults.go
Labels: ready-to-merge

#1593 .github/workflows: bump AKS BYOCNI workflow timeout
  .github/workflows/aks-byocni.yaml
Labels: ready-to-merge

#1595 Remove az-binary check
  .github/in-cluster-test-scripts/aks-byocni-install.sh
  install/autodetect.go
  install/azure.go
Labels: ready-to-merge

#1605 Farewell dependabot 👋
  .github/dependabot.yml
Labels: ready-to-merge

#1606 Add a function to check if the CLI is in Helm mode
  internal/cli/cmd/clustermesh.go
  internal/cli/cmd/cmd.go
  internal/cli/cmd/hubble.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: ready-to-merge

#1617 uninstall: allow ciliumVersion to start with "v"
  install/uninstall.go
Labels: kind/bug, ready-to-merge

#1537 Add support for CiliumCIDRGroup CRD
  k8s/client.go
  sysdump/client.go
  sysdump/constants.go
  sysdump/sysdump.go
  sysdump/sysdump_test.go
Labels: needs-rebase

#1634 sysdump: Don't save cilium-etcd-secrets
  sysdump/sysdump.go
Labels: ready-to-merge

#1654 ci: fix gke network starvation
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge, area/CI

#1651 check: make (Service)Address() return an IP address
  connectivity/check/peer.go
Labels: ready-to-merge, area/CI

#1655 check: update tunneling detection logic
  connectivity/check/features.go
Labels: ready-to-merge, area/CI

#1680 CI: Change multicluster provisioning to none blocking mode
  .github/workflows/multicluster.yaml
Labels: ready-to-merge, area/CI

#1681 CI: Simplify Junit uploads
  .github/workflows/kind.yaml
Labels: ready-to-merge, area/CI
