Repository cilium/cilium-cli, pull requests merged in 2023-06, with the labels that each got.

#1678 Prepare for v0.14.6 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#1703 status: Print Helm chart version in Helm mode
  internal/helm/helm.go
  status/k8s.go
  status/status.go
Labels: ready-to-merge

#1699 Make CI test resources unique for retries.
  .github/workflows/aks-byocni.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#1722 Update stable release to v0.14.7
  stable.txt
Labels: ready-to-merge

#1734 clustermesh enable: add enable-kvstoremesh flag
  clustermesh/clustermesh.go
  internal/cli/cmd/clustermesh.go
Labels: area/clustermesh, priority/release-blocker

#1706 while applying policies, wait for all expected policy revisions.
  connectivity/check/policy.go
Labels: ready-to-merge

#1736 connectivity: Add checks for agent error logs and drops due to missed tail calls
  connectivity/suite.go
  connectivity/tests/errors.go
Labels: area/CI

#1744 install: Normalize --helm-* flags
  internal/cli/cmd/install.go
  internal/cli/cmd/install_test.go
Labels: priority/release-blocker

#1742 Minor fixes for error messages on failure to disable Hubble
  internal/cli/cmd/install.go
Labels: sig/hubble

#1746 connectivity: Address migrate-svc changes
  connectivity/check/deployment.go
  connectivity/tests/upgrade.go
Labels: area/CI

#1755 renovate: let renovate update default Cilium version
  .github/renovate.json5
  .github/workflows/aks-byocni.yaml
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
  .github/workflows/externalworkloads.yaml
  .github/workflows/gke.yaml
  .github/workflows/kind.yaml
  .github/workflows/multicluster.yaml
  defaults/defaults.go
Labels: priority/release-blocker

#1768 connectivity: Add op=Exists toleration for test-conn-disrupt
  connectivity/check/deployment.go
Labels: area/CI

#1777 connectivity: Fix trailing newline in tail call drop counts
  connectivity/tests/errors.go
Labels: area/CI
