Repository cilium/cilium-cli, pull requests merged in 2023-08, with the labels that each got.

#1882 Update the error log exceptions
  connectivity/tests/errors.go
Labels: ready-to-merge

#1885 renovate: Don't update golang.org/x/exp
  .github/renovate.json5
Labels: priority/release-blocker

#1799 Expand warning about big sysdump
  sysdump/sysdump.go
Labels: ready-to-merge

#1910 Update missing dependencies to Go 1.21
  .golangci.yml
  Dockerfile
  Makefile
Labels: ready-to-merge

#1889 implement helm get values with sysdump
  internal/cli/cmd/sysdump.go
  k8s/client.go
  sysdump/client.go
  sysdump/constants.go
  sysdump/defaults.go
  sysdump/sysdump.go
  sysdump/sysdump_test.go
  vendor/helm.sh/helm/v3/pkg/cli/output/output.go
  vendor/modules.txt
Labels: ready-to-merge

#1942 connectivity: Add secondary network NodePort tests
  connectivity/check/check.go
  connectivity/check/context.go
  connectivity/check/deployment.go
  connectivity/tests/service.go
  internal/cli/cmd/connectivity.go
Labels: ready-to-merge, area/CI

#1943 connectivity: Use slices.Clone
  connectivity/tests/service.go
Labels: area/CI
