Repository cilium/cilium-cli, pull requests merged in 2023-01, with the labels that each got.

#1317 hubble: port-forward only to localhost
  hubble/relay.go
  hubble/ui.go
Labels: ready-to-merge, kind/enhancement

#1305 all: fix spacing with ℹ️ logs
  clustermesh/clustermesh.go
  install/autodetect.go
  install/azure.go
  install/install.go
Labels: ready-to-merge

#1322 hubble: port-forward only on IPv4
  hubble/relay.go
  hubble/ui.go
Labels: kind/enhancement

#1267 Make pod to world test configurable
  connectivity/check/check.go
  connectivity/manifests/client-egress-l7-http-named-port.yaml
  connectivity/manifests/client-egress-l7-http.yaml
  connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
  connectivity/suite.go
  connectivity/tests/world.go
  internal/cli/cmd/connectivity.go
  internal/utils/template.go
Labels: ready-to-merge

#1326 connectivity: Fix node2node test case feat requirement
  connectivity/suite.go
Labels: area/CI

#1327 Update stable release to v0.12.12
  stable.txt
Labels: ready-to-merge

#1301 connectivity: Display last error after waiting k8s resources timeouts
  connectivity/check/deployment.go
Labels: ready-to-merge

#1333 install: Auto-enable BPF masquerade
  install/autodetect.go
Labels: kind/enhancement

#1338 install: Do not enable BPF masq if ipv6 is enabled
  install/autodetect.go
Labels: area/CI, ci/hyperjump

#1339 connectivity: Set PreferDualStack for test services
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI, ci/hyperjump

#997 fix(connectivity): Add node-local-dns entitiy match for local ip usage case
  .gitignore
  connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
  connectivity/manifests/allow-all-except-world.yaml
  connectivity/manifests/client-egress-only-dns.yaml
  connectivity/manifests/client-egress-to-echo.yaml
  connectivity/manifests/client-egress-to-entities-world.yaml
  connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
Labels: ready-to-merge

#1356 status: rename Hubble status to Hubble Relay
  status/status.go
Labels: kind/enhancement
