Repository cilium/cilium-cli, pull requests merged in 2023-07, with the labels that each got.

#1771 helm mode: don't suggest removed Azure flag
  install/azure.go
Labels: ready-to-merge

#1801 connectivity: don't wait for service backends if the IP family is disabled
  connectivity/check/deployment.go
  connectivity/check/features.go
  connectivity/check/wait.go
Labels: kind/bug

#1802 Create a separate RESTClientGetter for Helm client
  clustermesh/clustermesh.go
  hubble/hubble.go
  internal/cli/cmd/install.go
  k8s/client.go
  status/k8s.go
Labels: priority/release-blocker

#1797 connectivity: Ignore failedToListCRDs error
  connectivity/tests/errors.go
Labels: area/CI

#1774 connectivity: Remove test-conn-disrupt tolerations
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#1817 Eksctl version pinned.
  .github/workflows/eks-tunnel.yaml
  .github/workflows/eks.yaml
Labels: ready-to-merge

#1822 GHA: fix 'install-cilium-cli' issue when building from source
  action.yaml
Labels: ready-to-merge

#1812 Fix pod summary for large numbers of pods
  k8s/client.go
  k8s/tables.go
Labels: ready-to-merge

#1778 connectivity: Use readiness probe for test-conn-disrupt-server
  connectivity/check/deployment.go
Labels: ready-to-merge, area/CI

#1842 Partly revert "connectivity: enable IPv6 test fort per-endpoint routing"
  connectivity/check/test.go
Labels: area/CI

#1843 Prepare for v0.15.3 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#1849 Prepare for v0.15.4 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#1854 connectivity: Fix fetching of XFRM counters
  connectivity/tests/ipsec_xfrm.go
Labels: ready-to-merge, area/CI

#1856 connectivity: Hide --flush-ct
  internal/cli/cmd/connectivity.go
Labels: area/CI

#1865 kind: Upload all the sysdumps
  .github/workflows/kind.yaml
Labels: ready-to-merge
