Repository cilium/cilium-cli, pull requests merged in 2023-04, with the labels that each got.

#1501 Use --set-string for node affinity
  connectivity/check/delete.go
  defaults/defaults.go
  install/helm.go
Labels: ready-to-merge

#1510 connectivity: Make detected Cilium Agent version available for feature detection
  connectivity/check/context.go
  connectivity/check/features.go
  connectivity/suite.go
Labels: kind/bug

#1505 Add connectivity tests for auth
  connectivity/check/features.go
  connectivity/check/policy.go
  connectivity/manifests/echo-ingress-auth-fail.yaml
  connectivity/manifests/echo-ingress-mtls.yaml
  connectivity/suite.go
Labels: area/servicemesh

#1500 BGP: Introduce new cli to get bgp peering state
  CODEOWNERS
  bgp/bgp.go
  bgp/peers.go
  bgp/peers_test.go
  internal/cli/cmd/bgp.go
  internal/cli/cmd/cmd.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: ready-to-merge

#1504 Add documentation for helm installation mode
  README.md
Labels: priority/release-blocker

#1528 defaults: bump json-mock to 1.3.5
  defaults/defaults.go
Labels: area/CI

#1529 fixes versioncheck for l7 proxy disabling with wireguard encryption
  install/helm.go
Labels: ready-to-merge

#1550 Allow the Helm timeout to be set on uninstall
  defaults/defaults.go
  install/uninstall.go
  internal/cli/cmd/install.go
Labels: ready-to-merge

#1543 connectivity: Retry on inconclusive results
  connectivity/check/action.go
Labels: ready-to-merge
