Repository cilium/cilium-cli, pull requests merged in 2023-11, with the labels that each got.

#2073 connectivity: don't use an ephemeral port for the echo server
  connectivity/check/deployment.go
Labels: area/CI

#2055 connectivity: Misc enc test case changes
  connectivity/tests/encryption.go
  utils/features/features.go
Labels: ready-to-merge, area/CI

#2089 connectivity: Detect WG encap on >= 1.15
  connectivity/tests/encryption.go
Labels: area/CI

#2069 k8s/copy: check file size
  k8s/copy.go
Labels: ready-to-merge

#2052 sysdump: Add "serial" tasks support to enable trace data collection
  internal/cli/cmd/sysdump.go
  sysdump/constants.go
  sysdump/defaults.go
  sysdump/sysdump.go
Labels: ready-to-merge, kind/enhancement

#1402 fix(connectivity): add dns rules and change protocol to ANY
  connectivity/manifests/allow-all-except-world.yaml
  connectivity/manifests/client-egress-l7-tls.yaml
  connectivity/manifests/client-egress-only-dns.yaml
  connectivity/manifests/client-egress-to-echo.yaml
  connectivity/manifests/client-egress-to-entities-world.yaml
  connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
Labels: ready-to-merge

#2106 connectivity: Add more tests for Ingress Controller
  connectivity/manifests/deny-ingress-backend.yaml
  connectivity/manifests/deny-ingress-entity.yaml
  connectivity/suite.go
Labels: ready-to-merge

#2110 connectivity: Add exception to policy map recreation
  connectivity/tests/errors.go
Labels: ready-to-merge, area/CI

#1931 clustermesh: add support for max-connected-clusters
  clustermesh/clustermesh.go
  defaults/defaults.go
Labels: ready-to-merge

#2118 action: allow to specify release repository
  action.yaml
Labels: area/CI

#2091 e2e: add pod/container info in error form exec in pod.
  k8s/client.go
  k8s/exec.go
Labels: ready-to-merge

#2097 Make --nodes-without-cilium work with SPIRE
  defaults/defaults.go
  install/helm.go
Labels: ready-to-merge
