Repository cilium/cilium-cli, pull requests merged in 2024-07, with the labels that each got.

#2655 Add --disable-check flag back
  cli/install.go
Labels: ready-to-merge

#2660 kvstoremesh: don't disable by default
  cli/clustermesh.go
  clustermesh/clustermesh.go
Labels: ready-to-merge

#2605 connectivity: Add Port Range Tests
  connectivity/builder/builder.go
  connectivity/builder/client_egress_expression.go
  connectivity/builder/client_egress_expression_knp.go
  connectivity/builder/client_egress_l7.go
  connectivity/builder/client_egress_l7_method.go
  connectivity/builder/client_egress_l7_set_header.go
  connectivity/builder/client_egress_l7_tls_headers.go
  connectivity/builder/client_egress_to_echo_deny.go
  connectivity/builder/client_egress_to_echo_expression_deny.go
  connectivity/builder/client_egress_to_echo_service_account.go
  connectivity/builder/client_egress_to_echo_service_account_deny.go
  connectivity/builder/client_with_service_account_egress_to_echo.go
  connectivity/builder/client_with_service_account_egress_to_echo_deny.go
  connectivity/builder/echo_ingress_auth_always_fail.go
  connectivity/builder/echo_ingress_mutual_auth_spiffe.go
  connectivity/builder/manifests/client-egress-l7-http-matchheader-secret-port-range.yaml
  connectivity/builder/manifests/client-egress-l7-http-method-port-range.yaml
  connectivity/builder/manifests/client-egress-l7-http-port-range.yaml
  connectivity/builder/manifests/client-egress-l7-tls-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-deny-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-expression-deny-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-expression-knp-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-expression-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-service-account-deny-port-range.yaml
  connectivity/builder/manifests/client-egress-to-echo-service-account-port-range.yaml
  connectivity/builder/manifests/client-egress-to-entities-world-port-range.yaml
  connectivity/builder/manifests/client-egress-to-fqdns-port-ranges.yaml
  connectivity/builder/manifests/client-with-service-account-egress-to-echo-deny-port-range.yaml
  connectivity/builder/manifests/client-with-service-account-egress-to-echo-port-range.yaml
  connectivity/builder/manifests/echo-ingress-l7-http-from-anywhere-port-range.yaml
  connectivity/builder/manifests/echo-ingress-l7-http-port-range.yaml
  connectivity/builder/manifests/echo-ingress-mutual-authentication-fail-port-range.yaml
  connectivity/builder/manifests/echo-ingress-mutual-authentication-port-range.yaml
  connectivity/builder/north_south_loadbalancing_with_l7_policy.go
  connectivity/builder/to_entities_world.go
  utils/features/features.go
Labels: ready-to-merge

#2672 Add --disable-check flag to upgrade command
  cli/install.go
Labels: ready-to-merge

#2665 clustermesh: fix remote clusters configuration reset upon deactivation
  clustermesh/clustermesh.go
Labels: ready-to-merge

#2674 Update stable release to v0.16.13
  stable.txt
Labels: ready-to-merge

#2670 connectivity: Add echo-ingress-l7-via-hostport-with-encryption testcase
  connectivity/builder/echo_ingress_l7.go
Labels: ready-to-merge

#2686 connectivity: echo-ingress-l7-via-hostport-with-encryption only runs with cilium 1.16.0 or newer
  connectivity/builder/echo_ingress_l7.go
Labels: ready-to-merge

#2684 flags: Use option.NewNamedMapOptions
  cli/connectivity.go
  cli/connectivity_test.go
Labels: ready-to-merge

#2681 connectivity: perf deployment improved
  connectivity/check/deployment.go
Labels: ready-to-merge

#2680 connectivity: test namespace suffix
  .github/workflows/kind.yaml
  cli/connectivity.go
  cli/connectivity_test.go
Labels: ready-to-merge

#2704 connectivity: Assert BGP timer intervals in BGP connectivity tests
  connectivity/check/frr.go
  connectivity/tests/bgp.go
Labels: ready-to-merge

#2707 connectivity: single JUnit report
  cli/connectivity.go
  connectivity/check/context.go
  connectivity/check/junit.go
  connectivity/suite.go
Labels: ready-to-merge

#2710 Assign release-related files to cilium-cli-maintainers
  CODEOWNERS
Labels: ready-to-merge

#2712 connectivity: Fix ineffective version check in BGP tests
  connectivity/builder/bgp_control_plane.go
Labels: kind/bug, ready-to-merge

#2719 Pick up kindest/node:v1.21.10
  .github/kind-config.yaml
Labels: ready-to-merge

#2721 junit: collector fix
  connectivity/check/junit.go
Labels: ready-to-merge

#2620 Add multicast subcommand
  cli/cmd.go
  cli/multicast.go
  multicast/multicast.go
Labels: ready-to-merge, area/multicast

#2732 connectivity: Support multiple conditions
  connectivity/check/test.go
  connectivity/check/test_test.go
Labels: ready-to-merge
