Repository cilium/cilium-cli, pull requests merged in 2024-06, with the labels that each got.

#2573 Update stable release to v0.16.9
  stable.txt
Labels: ready-to-merge

#2571 fix: conn tests JUnit file name
  cli/connectivity.go
  utils/junit/junit.go
  utils/junit/junit_test.go
Labels: ready-to-merge

#2586 Prepare for v0.16.10 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#2596 gha: increase disk size for GKE clusters
  .github/workflows/gke.yaml
  .github/workflows/multicluster.yaml
Labels: ready-to-merge

#2409 connectivity: Extend pod-to-pod encryption tests (for WG)
  connectivity/builder/manifests/client-egress-l7-http-from-any.yaml
  connectivity/builder/pod_to_pod_encryption.go
Labels: ready-to-merge

#2608 connectivity: Display last assertion error on failure
  connectivity/check/action.go
Labels: ready-to-merge, area/CI

#2611 gh/workflows: Fix display img digest step
  .github/workflows/images.yaml
Labels: ready-to-merge, area/CI

#2621 [Connectivity] Refactor single node detection
  connectivity/check/context.go
Labels: ready-to-merge

#2627 action: Add an option to run cilium-cli inside a container
  .github/tools/cilium.sh
  .github/workflows/aks-byocni.yaml
  action.yaml
Labels: ready-to-merge

#2629 gke: Run cilium-cli inside a container
  .github/in-cluster-test-scripts/gke.sh
  .github/workflows/gke.yaml
Labels: ready-to-merge

#2630 external-workloads: Run cilium-cli inside a container
  .github/in-cluster-test-scripts/external-workloads-install.sh
  .github/in-cluster-test-scripts/external-workloads.sh
  .github/workflows/externalworkloads.yaml
Labels: ready-to-merge

#2633 connectivity: Ensure Hubble Relay is connected to all the nodes
  connectivity/check/context.go
Labels: ready-to-merge

#2632 multicluster: Run cilium-cli inside a container
  .github/in-cluster-test-scripts/multicluster.sh
  .github/workflows/multicluster.yaml
Labels: priority/release-blocker

#2634 Dockerfile: Fix a warning
  Dockerfile
Labels: ready-to-merge

#2647 Update stable release to v0.16.11
  stable.txt
Labels: ready-to-merge
