Repository cilium/cilium-cli, pull requests merged in 2024-04, with the labels that each got.

#2463 k8s: Remove Tetragon client
  go.mod
  go.sum
  k8s/client.go
  vendor/github.com/cilium/tetragon/pkg/k8s/LICENSE
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/doc.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.defaults.go
  vendor/modules.txt
Labels: ready-to-merge

#2442 sysdump: Collect helm metadata
  k8s/client.go
  sysdump/client.go
  sysdump/constants.go
  sysdump/sysdump.go
  sysdump/sysdump_test.go
Labels: kind/enhancement, area/sysdump

#2464 connectivity: introduce host firewall tests
  connectivity/builder/builder.go
  connectivity/builder/host_firewall_egress.go
  connectivity/builder/host_firewall_ingress.go
  connectivity/check/test.go
Labels: needs-rebase, ready-to-merge

#2267 connectivity: add endpointslice clustermesh sync test
  CODEOWNERS
  connectivity/builder/builder.go
  connectivity/builder/endpointslice-clustermesh-sync.go
  connectivity/check/context.go
  connectivity/check/deployment.go
  connectivity/check/wait.go
  connectivity/tests/clustermesh-endpointslice-sync.go
  utils/features/features.go
Labels: ready-to-merge

#2472 ci: Use zip output for windows releases
  Makefile
Labels: ready-to-merge

#2482 sysdump: Clarify sysdump worker-count defaults to the number of available CPUs.
  sysdump/sysdump.go
Labels: documentation, ready-to-merge

#2481 Split conn tests into chunks
  connectivity/builder/builder.go
  connectivity/suite.go
Labels: ready-to-merge

#2498 Move the test namespace deletion logic to the install package
  cli/install.go
  connectivity/check/context.go
  install/install.go
  install/uninstall.go
Labels: ready-to-merge

#2502 sysdump: Check --namespace flag for cilium-operator
  cli/sysdump.go
  sysdump/sysdump.go
Labels: ready-to-merge

#2507 Prepare for v0.16.5 release
  README.md
  RELEASE.md
Labels: ready-to-merge

#2510 Update stable release to v0.16.5
  stable.txt
Labels: ready-to-merge

#2501 k8s: remove unused filter functionality from k8sclient.CiliumLogs
  clustermesh/clustermesh.go
  connectivity/check/policy.go
  k8s/client.go
  status/k8s.go
  status/k8s_test.go
Labels: ready-to-merge

#2516 Prepare for v0.16.6 release
  README.md
  RELEASE.md
Labels: ready-to-merge
