Repository cilium/cilium-cli, pull requests merged in 2024-03, with the labels that each got.

#2350 sniffer: always dump captured packets in assert mode
  utils/sniff/sniffer.go
Labels: ready-to-merge

#2363 Add error log check exception for leader election errors.
  connectivity/tests/errors.go
Labels: ready-to-merge

#2367 refactor: Move internal/cli to cli/
  cli/bgp.go
  cli/clustermesh.go
  cli/cmd.go
  cli/config.go
  cli/connectivity.go
  cli/context.go
  cli/encrypt.go
  cli/hooks.go
  cli/hubble.go
  cli/install.go
  cli/install_test.go
  cli/status.go
  cli/sysdump.go
  cli/utils.go
  cli/version.go
  internal/cli/cmd/cmd.go
Labels: ready-to-merge

#2397 Add InitializeCommand hook
  cli/cmd.go
  cli/cmd_test.go
  cli/hooks.go
Labels: ready-to-merge

#2412 gha: increase Multicluster timeout
  .github/workflows/multicluster.yaml
Labels: ci/flake

#2418 refactor: Move logging outside internal
  cmd/cilium/main.go
  logging/logging.go
Labels: ready-to-merge

#2432 tests: Add exceptions for error logs check
  connectivity/tests/errors.go
Labels: ready-to-merge, area/CI, ci/flake

#2435 connectivity: don't hard-code ingress service NodePorts
  connectivity/check/deployment.go
Labels: ready-to-merge

#2445 Explicitly wait for ingress service creation
  connectivity/check/deployment.go
  connectivity/check/wait.go
Labels: ready-to-merge

#2446 ci: avoid overlapping pod and service CIDRs on AKS
  .github/in-cluster-test-scripts/aks-byocni-install.sh
Labels: area/CI

#2448 Lock the connectivity command
  .github/workflows/dont-modify-connectivity.yaml
  connectivity/suite.go
Labels: ready-to-merge

#2456 Update stable release to v0.16.4
  stable.txt
Labels: ready-to-merge
